import dummydata
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column,String,DateTime,Integer,create_engine,ForeignKey
import os
from sqlalchemy.orm import sessionmaker



# DATABASE NAME
DB_NAME = "Login"
DB_USER_NAME = "LoginProjectUser"
DB_PASSWORD = "admin_123"  # NEED TO CHANGE IT TO ENCRYPTED PASSWORD
DB_TYPE = "mysql"
DB_DRIVER = "pymysql"
HOST_NAME = "127.0.0.1"
PORT_NAME = "3306"




connection_string= f"{DB_TYPE}+{DB_DRIVER}://{DB_USER_NAME}:{DB_PASSWORD}@{HOST_NAME}:{PORT_NAME}/{DB_NAME}"

Base= declarative_base()
metadata=Base.metadata

engine= create_engine(connection_string,echo=True)
Session=sessionmaker(bind=engine)
session=Session()
''' 
class user
autogenerated id, first name, last name, emailid, phone number, password id 

'''

class User(Base):
    __tablename__='userdata'
    id=Column(Integer, primary_key=True, unique=True)
    username= Column(String(100),nullable=False,unique=True)
    fname= Column(String(150),nullable= False)
    lname= Column(String(150))
    email= Column(String(150),nullable=False,unique=True)
    phone= Column(String(10),nullable=False,unique=True)
    lastlogin= Column(DateTime())
    lastlogout= Column(DateTime())
    passid= Column(Integer,foreign_key=True)

class PasswordList(Base):
    __tablename__= 'passwordlist'
    passid= Column( Integer,primary_key=True,unique=True)
    pass1= Column(String(150),nullable= False)
    pass2= Column(String(150))
    pass3= Column(String(150))





Base.metadata.create_all(bind=engine)
l=[]
for i in range(0,10):
    data = dummydata.createdummydata()
    user=User(username=data[0],
              fname=data[1],
              lname=data[2],
              email=data[3],
              phone=data[4],
              lastlogin=data[5],
              lastlogout=data[6],
              passid=1)
    l.append(user)
session.add_all(l)
session.commit()
